type LocaleCode = 'cs' | 'sk' | 'en' | 'he' | 'pl';
type Translations = { [key: string]: string };

const i18n: Record<LocaleCode, Translations> = {
    cs: {
      'scriptName': 'WME Speeds',
      //'layerName': 'Rychlosti',
      //'tabName': 'R',
      'speedsHeadline': 'Barvy segmentů dle rychlostí',
      'forumLink': '<a href="https://www.waze.com/forum/viewtopic.php?f=22&t=166406" target="_blank">České fórum</a>',
      'author': 'Autor: <a href="https://www.waze.com/user/editor/martinkolar" target="_blank">martinkolar (5)</a>',
      'version': 'Verze:',
      'invertSpeedsTitleNonDrivable': 'Zobrazit pouze segmenty bez rychlostí',
      'hideWithoutSpeeds': 'Skrýt segmenty bez rychlostí',
      //'invertSpeedsContentNonDrivable': 'Zvýrazní jen segmenty bez rychlosti (sjízdné) (červená)',
      //'invertSpeedsTitle': 'Invertovat barvy rychlostí (všechny segmenty)',
      //'invertSpeedsContent': 'Zvýrazní jen segmenty bez rychlosti (nesjízdné) (červená)',
      //'noSpeedsSegmentsTitle': 'Nesjízdné segmenty s rychlostí',
      //'noSpeedsSegmentsContent': 'Zvýrazní nesjízdné segmenty s rychlostmi (růžová)',
      'noSpeedsSegmentsOtherTitle': 'Skrýt rychlosti na nedůležitých segmentech',
      //'noSpeedsSegmentsOtherContent': 'Zvýrazní jinak sjízdné segmenty s rychlostmi (růžová)',
      'transparentColorsTitle': 'Průsvitné barvy',
      //'transparentColorsContent': 'Průsvitné barvy',
      //'unverifiedSegmentsTitle': 'Nepotvrzené rychlosti na segmentech',
      //'unverifiedSegmentsContent': 'Zvýrazní nepotvrzené rychlosti na segmentech'
    },
    sk: {
      'tabName': 'R',
      'speedsHeadline': 'Farby segmentov podľa rýchlostí',
      'forumLink': '<a href="https://www.waze.com/forum/viewtopic.php?f=22&t=166406" target="_blank">České fórum</a>',
      'author': 'Autor: <a href="https://www.waze.com/user/editor/martinkolar" target="_blank">martinkolar (CZ)</a>',
      'version': 'Verzia:',
      'invertSpeedsTitleNonDrivable': 'Invertovať farby rýchlostí (pouze s možností nastavení rychlosti)',
      'invertSpeedsContentNonDrivable': 'Zvýrazní iba segmenty bez rýchlosti (sjízdné) (červená)',
      'invertSpeedsTitle': 'Invertovať farby rýchlostí',
      'invertSpeedsContent': 'Zvýrazní iba segmenty bez rýchlosti (červená)',
      'noSpeedsSegmentsTitle': 'Nezjazdné segmenty s rýchlosťou',
      'noSpeedsSegmentsContent': 'Zvýrazní nezjazdné segmenty s rýchlosťami (ružová)',
      'noSpeedsSegmentsOtherTitle': 'Inak zjazdné segmenty s rýchlosťou',
      'noSpeedsSegmentsOtherContent': 'Zvýrazní inak zjazdné segmenty s rýchlosťami (ružová)',
      'transparentColorsTitle': 'Priehľadné farby',
      'transparentColorsContent': 'Spriehľadniť farby rýchlostí',
      'unverifiedSegmentsTitle': 'Nepotvrdené rýchlosti na segmentoch',
      'unverifiedSegmentsContent': 'Zvýrazniť nepotvrdené rýchlosti na segmentoch',
      'scriptName': 'WME Speeds',
      'layerName': 'Rýchlosti'
    },
    en: {
      'scriptName': 'WME Speeds',
      //'layerName': 'Speeds'
      //'tabName': 'S',
      'speedsHeadline': 'Colors by speed',
      'forumLink': '<a href="https://www.waze.com/forum/viewtopic.php?f=819&t=166497" target="_blank">English discussion</a>',
      'author': 'Author: <a href="https://www.waze.com/user/editor/martinkolar" target="_blank">martinkolar (CZ)</a>',
      'version': 'Version:',
      'invertSpeedsTitleNonDrivable': 'Show only segments without speeds',
      'hideWithoutSpeeds': 'Hide segments without speeds',
      //'invertSpeedsContentNonDrivable': 'Highlight segments without set speed (drivable) (red)',
      //'invertSpeedsTitle': 'Invert speed',
      //'invertSpeedsContent': 'Highlight segments without set speed (red)',
      //'noSpeedsSegmentsTitle': 'Non-drivable segments with speeds',
      //'noSpeedsSegmentsContent': 'Highlight non-drivable segments with set speed (pink)',
      'noSpeedsSegmentsOtherTitle': 'Hide speeds on other-drivable segments without speeds',
      //'noSpeedsSegmentsOtherContent': 'Highlight other-drivable segments with set speed (pink)',
      'transparentColorsTitle': 'Transparent color',
      //'transparentColorsContent': 'Make speed\'s colors transparent',
      //'unverifiedSegmentsTitle': 'Highlight unverified segments',
      //'unverifiedSegmentsContent': 'Highlight unverified segments',
    },
    he: {
      'tabName': 'S',
      'speedsHeadline': 'מקרא מהירויות לפי צבעים',
      'forumLink': '<a href="https://www.waze.com/forum/viewtopic.php?f=819&t=166497" target="_blank">דיון בפורום (אנגלית)</a>',
      'author': 'יוצר התוסף: martinkolar (CZ)',
      'version': 'גרסא:',
      'invertSpeedsTitleNonDrivable': 'הדגש את כל המקטעים ללא מהירות מוגדרת',
      'invertSpeedsContentNonDrivable': 'הדגש מקטעים מותרים לנהיגה ללא מהירות מוגדרת (אדום)',
      'invertSpeedsTitle': 'הפוך הגדרות',
      'invertSpeedsContent': 'הדגש מקטעים ללא מהירות מוגדרת (אדום)',
      'noSpeedsSegmentsTitle': 'מקטעים שאינם ניתנים לנהיגה עם מהירות מוגדרת',
      'noSpeedsSegmentsContent': 'הדגש מקטעים שאינם ניתנים לנהיגה עם מהירות מוגדרת (ורוד)',
      'noSpeedsSegmentsOtherTitle': 'אחר- מקטעים המותרים לנהיגה עם מהירות מוגדרת',
      'noSpeedsSegmentsOtherContent': 'הדגש מקטעים המותרים לנהיגה עם מהירות מוגדרת (ורוד)',
      'transparentColorsTitle': 'מצב שקיפות',
      'transparentColorsContent': 'הפעל מצב שקיפות צבעי מהירויות',
      'unverifiedSegmentsTitle': 'הדגש מקטעים לא מאומתים',
      'unverifiedSegmentsContent': 'הדגש מקטעים לא מאומתים',
      'scriptName': 'WME Speeds',
      'layerName': 'מהירויות'
    },
    pl: {
      'scriptName': 'WME Speeds',
      'layerName': 'Ograniczenia prękości',
      'tabName': 'P',
      'speedsHeadline': 'Kolory ograniczeń prędkości',
      'forumLink': 'Forum: <a href="https://www.waze.com/forum/viewtopic.php?f=819&t=166497" target="_blank">angielskie</a> | <a href="https://www.waze.com/forum/viewtopic.php?f=22&t=166406" target="_blank">czeskie</a>',
      'author': 'Autor: <a href="https://www.waze.com/user/editor/martinkolar" target="_blank">martinkolar (CZ)</a>',
      'version': 'Wersja:',
      'invertSpeedsTitleNonDrivable': 'Inwersja kolorów (tylko z opcją ograniczenia)',
      'invertSpeedsContentNonDrivable': 'Zaznacza drogi bez ustawionych ograniczeń prędkości z dostępną opcją ograniczenia (czerwony)',
      'invertSpeedsTitle': 'Inwersja kolorów',
      'invertSpeedsContent': 'Zaznacza drogi bez ustawionych ograniczeń prędkości (czerwony)',
      'noSpeedsSegmentsTitle': 'Nieprzejezdne drogi z prędkościami',
      'noSpeedsSegmentsContent': 'Zaznacza nieprzejezdne drogi z ustawionymi ograniczeniami prędkości (różowy)',
      'noSpeedsSegmentsOtherTitle': 'Inne przejezdne drogi z prędkościami',
      'noSpeedsSegmentsOtherContent': 'Zaznacza inne przejezdne drogi z ustawionymi ograniczeniami prędkości (różowy)',
      'transparentColorsTitle': 'Przeźroczyste kolory',
      'transparentColorsContent': 'Przeźroczyste kolory ograniczeń',
      'unverifiedSegmentsTitle': 'Niezweryfikowane prędkości',
      'unverifiedSegmentsContent': 'Wyróżnia segmenty z niezweryfikowanymi ograniczeniami prędkości'
  }
}

export function getTranslations(localeCode: string): Translations {
  return i18n[localeCode as LocaleCode] || i18n['en'];
}